# SPDX-FileCopyrightText: 2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = [
    ".github/FUNDING.yml",
    ".github/ISSUE_TEMPLATE/*.md",
    ".github/ISSUE_TEMPLATE/*.yml",
    ".gitignore",
    ".mailmap",
    "CHANGELOG.md",
    "README.md",
    "tests/*.json",
    "tests/*.org",
]
precedence = "override"
SPDX-FileCopyrightText = "2020-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
