name: CI

on:
  - push
  - pull_request

jobs:

  build:

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-12
          - macos-11
        emacs-version:
          - "27.1"
          - "27.2"
          - "snapshot"

    name: Emacs ${{ matrix.emacs-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: actions/checkout@v4

      - name: Compilation
        run: make compile

      - name: Tests
        run: make test
