# SPDX-FileCopyrightText: 2020-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on:
  - push
  - pull_request

jobs:

  build:

    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - macos-14
        emacs-version:
          - "28.1"
          - "28.2"
          - "29.1"
          - "29.2"
          - "29.3"
          - "29.4"
          - "snapshot"

    name: Emacs ${{ matrix.emacs-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: actions/checkout@v4

      - name: Compilation
        run: make compile

      - name: Tests
        run: make test
